/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: ['class', '[data-theme="dark"]', '[data-theme="black"]', '[data-theme="wind"]'],
  theme: {
    extend: {
      colors: {
        theme: {
          bg: {
            base: 'var(--bg-base)',
            surface: 'var(--bg-surface)',
            hover: 'var(--bg-surface-hover)',
            elevated: 'var(--bg-elevated)',
            overlay: 'var(--bg-overlay)',
            glass: 'var(--bg-glass)',
          },
          text: {
            primary: 'var(--text-primary)',
            secondary: 'var(--text-secondary)',
            muted: 'var(--text-muted)',
            disabled: 'var(--text-disabled)',
            placeholder: 'var(--text-placeholder)',
            inverse: 'var(--text-inverse)',
          },
          border: {
            base: 'var(--border-base)',
            light: 'var(--border-light)',
            focus: 'var(--border-focus)',
            hover: 'var(--border-hover)',
          },
          primary: {
            DEFAULT: 'var(--color-primary)',
            hover: 'var(--color-primary-hover)',
            light: 'var(--color-primary-light)',
            dark: 'var(--color-primary-dark)',
            bg: 'var(--color-primary-bg)',
            border: 'var(--color-primary-border)',
          },
          bull: {
            DEFAULT: 'var(--color-bull)',
            light: 'var(--color-bull-light)',
            bg: 'var(--color-bull-bg)',
            border: 'var(--color-bull-border)',
          },
          bear: {
            DEFAULT: 'var(--color-bear)',
            light: 'var(--color-bear-light)',
            bg: 'var(--color-bear-bg)',
            border: 'var(--color-bear-border)',
          },
          neutral: {
            DEFAULT: 'var(--color-neutral)',
            bg: 'var(--color-neutral-bg)',
            border: 'var(--color-neutral-border)',
          },
          warning: {
            DEFAULT: 'var(--color-warning)',
            bg: 'var(--color-warning-bg)',
            border: 'var(--color-warning-border)',
          },
          danger: {
            DEFAULT: 'var(--color-danger)',
            bg: 'var(--color-danger-bg)',
            border: 'var(--color-danger-border)',
          },
          success: {
            DEFAULT: 'var(--color-success)',
            bg: 'var(--color-success-bg)',
            border: 'var(--color-success-border)',
          },
          info: {
            DEFAULT: 'var(--color-info)',
            bg: 'var(--color-info-bg)',
            border: 'var(--color-info-border)',
          },
          chart: {
            bg: 'var(--chart-bg)',
            grid: 'var(--chart-grid)',
            text: 'var(--chart-text)',
            line: 'var(--chart-line)',
            area: 'var(--chart-area)',
            crosshair: 'var(--chart-crosshair)',
          },
          agent: {
            blue: 'var(--color-agent-blue)',
            'blue-hover': 'var(--color-agent-blue-hover)',
            'blue-bg': 'var(--color-agent-blue-bg)',
            'blue-border': 'var(--color-agent-blue-border)',
          },
        },
        bull: {
          DEFAULT: 'var(--color-bull)',
          light: 'var(--color-bull-light)',
          bg: 'var(--color-bull-bg)',
          border: 'var(--color-bull-border)',
        },
        bear: {
          DEFAULT: 'var(--color-bear)',
          light: 'var(--color-bear-light)',
          bg: 'var(--color-bear-bg)',
          border: 'var(--color-bear-border)',
        },
        primary: {
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          light: 'var(--color-primary-light)',
          dark: 'var(--color-primary-dark)',
          bg: 'var(--color-primary-bg)',
          border: 'var(--color-primary-border)',
        },
        agent: {
          blue: 'var(--color-agent-blue)',
          'blue-hover': 'var(--color-agent-blue-hover)',
          'blue-bg': 'var(--color-agent-blue-bg)',
          'blue-border': 'var(--color-agent-blue-border)',
        },
      },
      boxShadow: {
        'theme-sm': 'var(--shadow-sm)',
        'theme-md': 'var(--shadow-md)',
        'theme-lg': 'var(--shadow-lg)',
        'theme-xl': 'var(--shadow-xl)',
        'theme-glow': 'var(--shadow-glow)',
      },
      backgroundColor: {
        'base': 'var(--bg-base)',
        'surface': 'var(--bg-surface)',
        'surface-hover': 'var(--bg-surface-hover)',
        'elevated': 'var(--bg-elevated)',
        'overlay': 'var(--bg-overlay)',
        'glass': 'var(--bg-glass)',
        'bull': 'var(--color-bull-bg)',
        'bear': 'var(--color-bear-bg)',
        'primary': 'var(--color-primary-bg)',
        'terminal-bg': 'var(--bg-base)',
        'terminal-panel': 'var(--bg-surface)',
        'theme-primary': 'var(--bg-base)',
        'theme-secondary': 'var(--bg-surface)',
        'theme-panel': 'var(--bg-surface)',
        'agent-blue': 'var(--color-agent-blue-bg)',
      },
      textColor: {
        'primary': 'var(--text-primary)',
        'secondary': 'var(--text-secondary)',
        'muted': 'var(--text-muted)',
        'disabled': 'var(--text-disabled)',
        'placeholder': 'var(--text-placeholder)',
        'inverse': 'var(--text-inverse)',
        'bull': 'var(--color-bull)',
        'bear': 'var(--color-bear)',
        'accent': 'var(--color-primary)',
        'terminal': 'var(--text-primary)',
        'terminal-dim': 'var(--text-secondary)',
        'terminal-accent': 'var(--color-primary)',
        'theme-primary': 'var(--text-primary)',
        'theme-secondary': 'var(--text-secondary)',
        'theme-tertiary': 'var(--text-muted)',
        'agent-blue': 'var(--color-agent-blue)',
      },
      borderColor: {
        'base': 'var(--border-base)',
        'light': 'var(--border-light)',
        'focus': 'var(--border-focus)',
        'hover': 'var(--border-hover)',
        'bull': 'var(--color-bull-border)',
        'bear': 'var(--color-bear-border)',
        'primary': 'var(--color-primary-border)',
        'theme': 'var(--border-base)',
        'theme-secondary': 'var(--border-light)',
        'theme-hover': 'var(--border-hover)',
        'theme-accent': 'var(--color-primary-border)',
        'terminal-border': 'var(--border-base)',
        'agent-blue': 'var(--color-agent-blue-border)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      spacing: {
        'xs': 'var(--space-xs)',
        'sm': 'var(--space-sm)',
        'md': 'var(--space-md)',
        'lg': 'var(--space-lg)',
        'xl': 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
      },
      transitionDuration: {
        'micro': 'var(--duration-micro)',
        'fast': 'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow': 'var(--duration-slow)',
      },
      zIndex: {
        'base': 'var(--z-base)',
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'fixed': 'var(--z-fixed)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        'modal': 'var(--z-modal)',
        'popover': 'var(--z-popover)',
        'tooltip': 'var(--z-tooltip)',
        'toast': 'var(--z-toast)',
        'max': 'var(--z-max)',
      },
    },
  },
  plugins: [],
}
